name: Build-OpenWrt

on:
  push:
    branches: 
      - main
  workflow_dispatch:
#  release:
#    types: published
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started
#  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
#    timeout-minutes: 360

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Init Compilation Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost $AGENT_TOOLSDIRECTORY
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install dwarves quilt llvm clang lldb lld build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget ccache curl swig coreutils vim nano python3 python3-dev python3-pip python3-ply python3-pyelftools lrzsz scons
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    - name: Clone Source
      run: |
        cd /home/runner
        bash ${GITHUB_WORKSPACE}/clone_source.sh
        sudo chown -R runner:runner lede
    - name: Before Build
      run: |
        /bin/bash ${GITHUB_WORKSPACE}/before_build.sh
        cp -fpR ${GITHUB_WORKSPACE}/. /home/runner/lede/

#    - name: SSH connection to Actions
#      uses: csexton/debugger-action@master

    - name: Start Build
      run: | 
        cd /home/runner/lede
        mv .config .config_default
        rm -f .config.old
        config_names="$(ls .config*)"
        for i in $config_names;do mv -f $i .config; make defconfig; make -j$[$(nproc)+1]; rm -rf build_dir/target* build_dir/toolchain* staging_dir/target* staging_dir/toolchain*; done
    - name: After Build
      run: |
        /bin/bash /home/runner/lede/after_build.sh
    - name: Upload Packages
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: /home/runner/lede/bin/packages/
    - name: Upload Firmwares
      uses: actions/upload-artifact@3
      with:
        name: Firmwares
        path: /home/runner/lede/bin/targets/
